name: Manual UI Tests + Allure Report

on:
  workflow_dispatch:
    inputs:
      category:
        description: 'Выберите категорию тестов'
        required: true
        type: choice
        default: all
        options:
          - all
          - drop down
          - inputs
          - buttons
          - checkbox
          - select
          - new tab
          - text area
          - alerts
          - drag and drop
          - iframes
          - pop-up

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'          
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run selected tests
        run: |
          if [ "${{ inputs.category }}" = "all" ]; then
            pytest tests/ --alluredir=allure-results -v --tb=short
          else
            
            case "${{ inputs.category }}" in
              "drop down")   pytest tests/test_suie.py --alluredir=allure-results -v ;;
              inputs)        pytest tests/test_input.py --alluredir=allure-results -v ;;
              buttons)       pytest tests/test_buttons.py --alluredir=allure-results -v ;;
              checkbox)      pytest tests/test_checkbox.py --alluredir=allure-results -v ;;
              select)        pytest tests/test_select.py --alluredir=allure-results -v ;;
              "new tab")     pytest tests/test_new_tab.py --alluredir=allure-results -v ;;
              "text area")   pytest tests/test_text_area.py --alluredir=allure-results -v ;;
              alerts)        pytest tests/test_alerts.py --alluredir=allure-results -v ;;
              "drag and drop") pytest tests/test_drag_n_drop.py --alluredir=allure-results -v ;;
              iframes)       pytest tests/test_iframes.py --alluredir=allure-results -v ;;
              "pop-up")      pytest tests/test_popup.py --alluredir=allure-results -v ;;
              *) echo "Неизвестная категория"; exit 1 ;;
            esac
          fi

      - name: Upload allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 7

  generate-and-publish-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Download allure-results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Install Allure
        run: |
          curl -sL https://github.com/allure-framework/allure2/releases/download/2.32.2/allure-2.32.2.tgz | tar -xz -C /tmp
          sudo mv /tmp/allure-2.32.2 /opt/allure
          
      - name: Setup Allure PATH
          echo "/opt/allure/bin" >> $GITHUB_PATH
          allure --version

      - name: Generate Allure report
        run: allure generate allure-results -o public --clean || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
